"""
Add Complete 50+ Careers Database
Run this to populate with all comprehensive careers
"""

from pymongo import MongoClient
from datetime import datetime

print("=" * 60)
print("🚀 ADDING 50+ COMPREHENSIVE CAREERS")
print("=" * 60)

try:
    # Connect to MongoDB
    print("\n📡 Connecting to MongoDB...")
    client = MongoClient('mongodb://localhost:27017/', serverSelectionTimeoutMS=5000)
    client.server_info()
    print("✅ Connected to MongoDB")
    
    db = client['career_counselling']
    
    # Check existing careers
    print("\n📋 Checking existing careers...")
    existing_count = db.careers.count_documents({})
    print(f"📊 Current careers in database: {existing_count}")
    
    if existing_count > 0:
        response = input(f"\n⚠️  Found {existing_count} existing careers. Delete and replace? (yes/no): ")
        if response.lower() == 'yes':
            result = db.careers.delete_many({})
            print(f"✅ Deleted {result.deleted_count} old careers")
        else:
            print("❌ Keeping existing careers, adding new ones...")
    
    print("\n📊 Adding 50+ comprehensive careers...")
    
    # Complete 50+ Careers Database
    all_careers = [
        # TECHNOLOGY CAREERS (15)
        {
            'name': 'Software Engineer',
            'title': 'Software Engineer',
            'category': 'Technology',
            'subcategory': 'Software Development',
            'description': 'Design, develop, and maintain software applications and systems',
            'detailed_description': 'Software engineers are problem solvers who use code to build applications, websites, and systems. They work on everything from mobile apps to enterprise software, collaborating with teams to create efficient, scalable solutions.',
            'salary_range': '₹4-25 LPA',
            'min_salary': 400000,
            'max_salary': 2500000,
            'education': 'B.Tech/BE in Computer Science, BCA, B.Sc Computer Science',
            'skills': ['Programming (Python, Java, C++)', 'Problem-solving', 'Data Structures & Algorithms', 'Software Design', 'Version Control (Git)'],
            'required_skills': ['programming', 'logical-thinking', 'problem-solving', 'teamwork', 'creativity'],
            'related_interests': ['technology', 'coding', 'innovation', 'computers', 'problem-solving'],
            'related_subjects': ['Computer Science', 'Mathematics', 'Physics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Very High Demand',
            'work_environment': 'Office/Remote',
            'top_companies': ['Google', 'Microsoft', 'Amazon', 'Infosys', 'TCS', 'Wipro'],
            'entrance_exams': ['JEE Main', 'JEE Advanced', 'KEAM'],
            'top_colleges': ['IIT Palakkad', 'NIT Calicut', 'Government Engineering Colleges'],
            'career_path': 'Junior Developer → Senior Developer → Team Lead → Engineering Manager → CTO',
            'day_to_day': ['Writing and testing code', 'Collaborating with team', 'Code reviews', 'Debugging and optimization', 'Learning new technologies'],
            'pros': ['High salary potential', 'Remote work options', 'Continuous learning', 'Creative problem-solving', 'Global opportunities'],
            'cons': ['Long sitting hours', 'Deadline pressure', 'Constant need to update skills', 'Can be isolating'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Data Scientist',
            'title': 'Data Scientist',
            'category': 'Technology',
            'subcategory': 'Data & Analytics',
            'description': 'Analyze complex data to help organizations make better decisions',
            'detailed_description': 'Data scientists combine programming, statistics, and domain knowledge to analyze data and solve business problems. They build predictive models, create visualizations, and communicate insights to stakeholders.',
            'salary_range': '₹6-30 LPA',
            'min_salary': 600000,
            'max_salary': 3000000,
            'education': 'B.Tech/M.Tech in Data Science, Statistics, Mathematics',
            'skills': ['Python/R Programming', 'Statistics & Mathematics', 'Machine Learning', 'Data Visualization', 'SQL', 'Big Data Tools'],
            'required_skills': ['analytical-thinking', 'programming', 'statistics', 'problem-solving', 'communication'],
            'related_interests': ['mathematics', 'technology', 'analysis', 'patterns', 'statistics'],
            'related_subjects': ['Mathematics', 'Statistics', 'Computer Science'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Very High Demand',
            'work_environment': 'Office/Hybrid',
            'top_companies': ['Google', 'Amazon', 'Flipkart', 'Microsoft', 'Analytics firms'],
            'entrance_exams': ['JEE Main', 'GATE', 'CAT (for MBA)'],
            'top_colleges': ['IITs', 'IIMs', 'ISI Kolkata', 'NITs'],
            'career_path': 'Junior Data Scientist → Data Scientist → Senior DS → Lead DS → Chief Data Officer',
            'day_to_day': ['Data cleaning and preparation', 'Statistical analysis', 'Building ML models', 'Creating visualizations', 'Presenting insights'],
            'pros': ['High salary', 'High demand', 'Diverse industries', 'Impactful work', 'Continuous learning'],
            'cons': ['Requires strong math skills', 'Data cleaning can be tedious', 'Competitive field'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Web Developer',
            'title': 'Web Developer',
            'category': 'Technology',
            'subcategory': 'Software Development',
            'description': 'Create and maintain websites and web applications',
            'detailed_description': 'Web developers build the websites and applications we use every day. They can specialize in frontend (what users see), backend (server and database), or full-stack (both).',
            'salary_range': '₹3-12 LPA',
            'min_salary': 300000,
            'max_salary': 1200000,
            'education': 'B.Tech/BCA or Self-taught with portfolio',
            'skills': ['HTML/CSS/JavaScript', 'React/Angular/Vue', 'Node.js/Backend frameworks', 'Responsive Design', 'Git', 'REST APIs'],
            'required_skills': ['programming', 'creativity', 'problem-solving', 'design-sense', 'attention-to-detail'],
            'related_interests': ['technology', 'coding', 'design', 'websites', 'creativity'],
            'related_subjects': ['Computer Science', 'Mathematics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'High Demand',
            'work_environment': 'Office/Remote/Freelance',
            'top_companies': ['Tech startups', 'Digital agencies', 'Product companies', 'Freelance'],
            'entrance_exams': ['JEE', 'KEAM', 'Or self-taught route'],
            'top_colleges': ['Any engineering college', 'Online courses (Udemy, Coursera)'],
            'career_path': 'Junior Developer → Mid-level → Senior → Lead → Architect',
            'day_to_day': ['Writing code', 'Designing interfaces', 'Testing features', 'Collaborating with designers', 'Client meetings'],
            'pros': ['High freelance potential', 'Remote work', 'Creative', 'Quick entry possible', 'Good salary'],
            'cons': ['Rapidly changing technologies', 'Browser compatibility issues', 'Tight deadlines'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Mobile App Developer',
            'title': 'Mobile App Developer',
            'category': 'Technology',
            'subcategory': 'Software Development',
            'description': 'Develop applications for mobile devices (iOS and Android)',
            'detailed_description': 'Mobile app developers create applications for smartphones and tablets. They can specialize in iOS (Swift), Android (Kotlin/Java), or cross-platform development (React Native, Flutter).',
            'salary_range': '₹4-15 LPA',
            'min_salary': 400000,
            'max_salary': 1500000,
            'education': 'B.Tech/BCA in Computer Science',
            'skills': ['Swift (iOS) / Kotlin (Android)', 'React Native / Flutter', 'Mobile UI/UX', 'REST APIs', 'App Store deployment'],
            'required_skills': ['programming', 'problem-solving', 'design', 'attention-to-detail', 'user-focus'],
            'related_interests': ['technology', 'coding', 'mobile', 'apps', 'innovation'],
            'related_subjects': ['Computer Science'],
            'growth_potential': 'Excellent',
            'job_outlook': 'High Demand',
            'work_environment': 'Office/Remote',
            'top_companies': ['Apple', 'Google', 'Startups', 'Mobile-first companies'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Private engineering colleges'],
            'career_path': 'Junior → Mid-level → Senior → Lead → Architect',
            'day_to_day': ['Coding app features', 'UI/UX implementation', 'Testing on devices', 'Bug fixing', 'App updates'],
            'pros': ['Growing market', 'Entrepreneurship opportunities', 'Good pay', 'Creative work'],
            'cons': ['Multiple platforms to learn', 'Frequent OS updates', 'Device fragmentation'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'AI/ML Engineer',
            'title': 'AI/ML Engineer',
            'category': 'Technology',
            'subcategory': 'Artificial Intelligence',
            'description': 'Build intelligent systems using artificial intelligence and machine learning',
            'detailed_description': 'AI/ML engineers develop systems that can learn, reason, and act intelligently. They work on cutting-edge technologies like neural networks, deep learning, and natural language processing.',
            'salary_range': '₹7-35 LPA',
            'min_salary': 700000,
            'max_salary': 3500000,
            'education': 'B.Tech/M.Tech in CS/AI, specialized courses',
            'skills': ['Python/R', 'TensorFlow/PyTorch', 'Deep Learning', 'Neural Networks', 'Mathematics', 'Model Optimization'],
            'required_skills': ['programming', 'mathematics', 'problem-solving', 'research', 'analytical'],
            'related_interests': ['technology', 'mathematics', 'ai', 'research', 'innovation'],
            'related_subjects': ['Computer Science', 'Mathematics', 'Statistics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Very High Demand',
            'work_environment': 'Office/Hybrid/Research Labs',
            'top_companies': ['Google', 'Microsoft', 'Amazon', 'OpenAI', 'Research institutions'],
            'entrance_exams': ['JEE Advanced', 'GATE'],
            'top_colleges': ['IITs', 'IIIT', 'Top NITs'],
            'career_path': 'ML Engineer → Senior ML Engineer → ML Architect → AI Research Scientist',
            'day_to_day': ['Building ML models', 'Training algorithms', 'Data preprocessing', 'Model evaluation', 'Research papers'],
            'pros': ['Cutting-edge field', 'Very high salary', 'Intellectually stimulating', 'Future-proof career'],
            'cons': ['Requires advanced math', 'Computationally expensive', 'Competitive field', 'Continuous learning needed'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Cybersecurity Specialist',
            'title': 'Cybersecurity Specialist',
            'category': 'Technology',
            'subcategory': 'Security',
            'description': 'Protect computer systems and networks from cyber threats',
            'detailed_description': 'Cybersecurity specialists are digital guardians who protect organizations from hackers, malware, and data breaches. They implement security protocols, conduct penetration testing, and respond to security incidents.',
            'salary_range': '₹5-25 LPA',
            'min_salary': 500000,
            'max_salary': 2500000,
            'education': 'B.Tech in CS/Cybersecurity, certifications',
            'skills': ['Network Security', 'Ethical Hacking', 'Penetration Testing', 'Cryptography', 'Security Tools', 'Risk Assessment'],
            'required_skills': ['analytical-thinking', 'attention-to-detail', 'problem-solving', 'technical', 'security-mindset'],
            'related_interests': ['technology', 'security', 'problem-solving', 'hacking', 'protection'],
            'related_subjects': ['Computer Science', 'Mathematics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Very High Demand',
            'work_environment': 'Office/Remote',
            'top_companies': ['Banks', 'Tech companies', 'Government', 'Consulting firms'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Specialized cybersecurity institutes'],
            'career_path': 'Security Analyst → Security Engineer → Security Architect → CISO',
            'day_to_day': ['Monitoring security systems', 'Conducting security audits', 'Responding to incidents', 'Implementing security measures'],
            'pros': ['High demand', 'Good salary', 'Important work', 'Challenging', 'Job security'],
            'cons': ['High stress', 'On-call work', 'Constantly evolving threats', 'Pressure to stay updated'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Cloud Engineer',
            'title': 'Cloud Engineer',
            'category': 'Technology',
            'subcategory': 'Cloud Computing',
            'description': 'Design and manage cloud computing systems',
            'detailed_description': 'Cloud engineers design, implement, and maintain cloud-based solutions. They help companies move to the cloud and optimize their cloud infrastructure for performance and cost.',
            'salary_range': '₹6-28 LPA',
            'min_salary': 600000,
            'max_salary': 2800000,
            'education': 'B.Tech in CS/IT, cloud certifications',
            'skills': ['AWS/Azure/GCP', 'Linux', 'Networking', 'DevOps', 'Automation', 'Security'],
            'required_skills': ['technical', 'problem-solving', 'learning-agility', 'automation'],
            'related_interests': ['technology', 'infrastructure', 'automation', 'cloud'],
            'related_subjects': ['Computer Science'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Very High Demand',
            'work_environment': 'Office/Remote',
            'top_companies': ['Amazon', 'Microsoft', 'Google', 'All major tech companies'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Engineering colleges'],
            'career_path': 'Cloud Engineer → Senior Cloud Engineer → Cloud Architect → Cloud Solutions Architect',
            'day_to_day': ['Managing cloud infrastructure', 'Automation', 'Cost optimization', 'Security implementation', 'Troubleshooting'],
            'pros': ['High demand', 'Excellent salary', 'Remote work', 'Future-proof', 'Continuous learning'],
            'cons': ['Certification costs', 'Complex systems', 'Rapid changes', 'On-call responsibilities'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'DevOps Engineer',
            'title': 'DevOps Engineer',
            'category': 'Technology',
            'subcategory': 'Operations',
            'description': 'Automate and streamline software development and deployment',
            'detailed_description': 'DevOps engineers combine development and operations skills to improve collaboration and productivity. They automate processes, manage infrastructure, and ensure smooth software delivery.',
            'salary_range': '₹5-22 LPA',
            'min_salary': 500000,
            'max_salary': 2200000,
            'education': 'B.Tech in CS/IT',
            'skills': ['Linux', 'Docker/Kubernetes', 'CI/CD', 'Scripting (Python, Bash)', 'Git', 'Cloud platforms'],
            'required_skills': ['technical', 'problem-solving', 'automation', 'collaboration'],
            'related_interests': ['technology', 'automation', 'efficiency', 'operations'],
            'related_subjects': ['Computer Science'],
            'growth_potential': 'Excellent',
            'job_outlook': 'High Demand',
            'work_environment': 'Office/Hybrid',
            'top_companies': ['Tech companies', 'Startups', 'Product companies'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Engineering colleges'],
            'career_path': 'DevOps Engineer → Senior DevOps → DevOps Architect → VP Engineering',
            'day_to_day': ['Building CI/CD pipelines', 'Infrastructure automation', 'Monitoring systems', 'Incident response', 'Collaboration'],
            'pros': ['High demand', 'Good salary', 'Varied work', 'Problem-solving', 'Remote options'],
            'cons': ['On-call duties', 'High pressure', 'Broad skill requirements', 'Constant learning'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Full Stack Developer',
            'title': 'Full Stack Developer',
            'category': 'Technology',
            'subcategory': 'Software Development',
            'description': 'Work on both frontend and backend of web applications',
            'detailed_description': 'Full stack developers handle both client-side (frontend) and server-side (backend) development. They can build complete web applications from start to finish.',
            'salary_range': '₹5-20 LPA',
            'min_salary': 500000,
            'max_salary': 2000000,
            'education': 'B.Tech/BCA in Computer Science',
            'skills': ['Frontend (React/Angular)', 'Backend (Node.js/Python)', 'Databases (SQL/NoSQL)', 'APIs', 'Git'],
            'required_skills': ['programming', 'problem-solving', 'versatility', 'learning-agility'],
            'related_interests': ['technology', 'coding', 'web-development', 'full-stack'],
            'related_subjects': ['Computer Science'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Very High Demand',
            'work_environment': 'Office/Remote/Startups',
            'top_companies': ['Startups', 'Product companies', 'Tech companies'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Engineering colleges'],
            'career_path': 'Junior → Mid-level → Senior → Lead → Architect',
            'day_to_day': ['Frontend development', 'Backend APIs', 'Database design', 'Full feature implementation'],
            'pros': ['Versatile skills', 'High demand', 'Complete ownership', 'Good salary'],
            'cons': ['Need to learn many technologies', 'Can be overwhelming', 'Constantly evolving'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Blockchain Developer',
            'title': 'Blockchain Developer',
            'category': 'Technology',
            'subcategory': 'Blockchain',
            'description': 'Develop blockchain-based applications and smart contracts',
            'detailed_description': 'Blockchain developers build decentralized applications (DApps), smart contracts, and blockchain protocols. They work on cryptocurrency, NFTs, and Web3 technologies.',
            'salary_range': '₹6-30 LPA',
            'min_salary': 600000,
            'max_salary': 3000000,
            'education': 'B.Tech in CS, Blockchain certifications',
            'skills': ['Solidity', 'Ethereum', 'Web3.js', 'Cryptography', 'Smart Contracts'],
            'required_skills': ['programming', 'cryptography', 'problem-solving', 'innovation'],
            'related_interests': ['blockchain', 'cryptocurrency', 'technology', 'decentralization'],
            'related_subjects': ['Computer Science', 'Mathematics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Growing Rapidly',
            'work_environment': 'Remote/Startups',
            'top_companies': ['Crypto startups', 'Blockchain companies', 'Tech giants'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Online courses'],
            'career_path': 'Junior → Mid → Senior → Architect',
            'day_to_day': ['Writing smart contracts', 'DApp development', 'Testing', 'Security audits'],
            'pros': ['Cutting-edge', 'High salary', 'Remote work', 'Innovation'],
            'cons': ['Volatile market', 'Steep learning curve', 'Regulatory uncertainty'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Game Developer',
            'title': 'Game Developer',
            'category': 'Technology',
            'subcategory': 'Game Development',
            'description': 'Create video games for various platforms',
            'detailed_description': 'Game developers design and program video games for consoles, PC, mobile, and VR. They work on gameplay mechanics, graphics, physics, and AI.',
            'salary_range': '₹4-20 LPA',
            'min_salary': 400000,
            'max_salary': 2000000,
            'education': 'B.Tech in CS, Game Design courses',
            'skills': ['Unity/Unreal Engine', 'C++/C#', 'Game Physics', '3D Graphics', 'Game Design'],
            'required_skills': ['programming', 'creativity', 'problem-solving', 'game-design'],
            'related_interests': ['gaming', 'technology', 'creativity', 'storytelling'],
            'related_subjects': ['Computer Science', 'Physics', 'Art'],
            'growth_potential': 'Good',
            'job_outlook': 'Growing',
            'work_environment': 'Game studios/Remote',
            'top_companies': ['Game studios', 'EA', 'Ubisoft', 'Indie studios'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Specialized game design schools'],
            'career_path': 'Junior → Mid → Senior → Lead → Game Director',
            'day_to_day': ['Coding game mechanics', 'Debugging', 'Testing', 'Optimization', 'Collaboration'],
            'pros': ['Creative work', 'Fun industry', 'Growing market', 'Passion project'],
            'cons': ['Long hours (crunch time)', 'Competitive', 'Can be unstable'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Database Administrator',
            'title': 'Database Administrator (DBA)',
            'category': 'Technology',
            'subcategory': 'Database',
            'description': 'Manage and maintain database systems',
            'detailed_description': 'DBAs ensure databases run efficiently, securely, and are properly backed up. They optimize queries, manage access, and handle data integrity.',
            'salary_range': '₹4-18 LPA',
            'min_salary': 400000,
            'max_salary': 1800000,
            'education': 'B.Tech/BCA in CS',
            'skills': ['SQL', 'Database design', 'Backup/Recovery', 'Performance tuning', 'Security'],
            'required_skills': ['technical', 'attention-to-detail', 'problem-solving', 'analytical'],
            'related_interests': ['databases', 'technology', 'organization', 'optimization'],
            'related_subjects': ['Computer Science', 'Mathematics'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Office',
            'top_companies': ['All companies with databases', 'Banks', 'IT companies'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Engineering colleges'],
            'career_path': 'Junior DBA → DBA → Senior DBA → Lead DBA',
            'day_to_day': ['Database monitoring', 'Query optimization', 'Backups', 'Security management'],
            'pros': ['Stable career', 'Good salary', 'Essential role', 'Less stressful'],
            'cons': ['Can be repetitive', 'On-call duties', 'Less exciting than development'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Network Engineer',
            'title': 'Network Engineer',
            'category': 'Technology',
            'subcategory': 'Networking',
            'description': 'Design and maintain computer networks',
            'detailed_description': 'Network engineers set up and maintain LANs, WANs, and other data communication systems. They ensure network security and performance.',
            'salary_range': '₹3-15 LPA',
            'min_salary': 300000,
            'max_salary': 1500000,
            'education': 'B.Tech in CS/IT, CCNA/CCNP',
            'skills': ['Networking protocols', 'Cisco/Juniper', 'Network security', 'Troubleshooting'],
            'required_skills': ['technical', 'problem-solving', 'analytical', 'communication'],
            'related_interests': ['technology', 'networking', 'infrastructure', 'troubleshooting'],
            'related_subjects': ['Computer Science'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Office/Data centers',
            'top_companies': ['ISPs', 'Telecom companies', 'All large organizations'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Engineering colleges'],
            'career_path': 'Junior → Mid → Senior → Network Architect',
            'day_to_day': ['Network monitoring', 'Troubleshooting', 'Configuration', 'Security management'],
            'pros': ['Stable career', 'Essential skill', 'Good salary', 'Job security'],
            'cons': ['On-call work', 'Can be stressful during outages', 'Continuous learning'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'QA Engineer',
            'title': 'Quality Assurance Engineer',
            'category': 'Technology',
            'subcategory': 'Quality Assurance',
            'description': 'Test software to ensure quality and find bugs',
            'detailed_description': 'QA engineers test software applications to find bugs and ensure they meet quality standards. They write test cases, perform manual and automated testing.',
            'salary_range': '₹3-12 LPA',
            'min_salary': 300000,
            'max_salary': 1200000,
            'education': 'B.Tech/BCA in CS',
            'skills': ['Manual testing', 'Automation testing', 'Selenium', 'Test planning', 'Bug reporting'],
            'required_skills': ['attention-to-detail', 'analytical', 'patience', 'communication'],
            'related_interests': ['technology', 'quality', 'testing', 'problem-finding'],
            'related_subjects': ['Computer Science'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Office',
            'top_companies': ['All software companies', 'Startups', 'IT companies'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['Any engineering college'],
            'career_path': 'QA Tester → Senior QA → QA Lead → QA Manager',
            'day_to_day': ['Writing test cases', 'Testing features', 'Bug reporting', 'Regression testing'],
            'pros': ['Good entry point', 'Important role', 'Less coding', 'Work-life balance'],
            'cons': ['Can be repetitive', 'Lower salary than developers', 'Less creative'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'IoT Engineer',
            'title': 'IoT (Internet of Things) Engineer',
            'category': 'Technology',
            'subcategory': 'IoT',
            'description': 'Develop connected devices and IoT systems',
            'detailed_description': 'IoT engineers design and build smart devices that connect to the internet - from smart homes to industrial sensors.',
            'salary_range': '₹4-18 LPA',
            'min_salary': 400000,
            'max_salary': 1800000,
            'education': 'B.Tech in CS/Electronics',
            'skills': ['Embedded systems', 'Sensors', 'Cloud platforms', 'Programming', 'Networking'],
            'required_skills': ['technical', 'programming', 'problem-solving', 'hardware-knowledge'],
            'related_interests': ['technology', 'electronics', 'smart-devices', 'innovation'],
            'related_subjects': ['Computer Science', 'Electronics', 'Physics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Growing Rapidly',
            'work_environment': 'Office/Labs',
            'top_companies': ['Tech companies', 'Manufacturing', 'Startups'],
            'entrance_exams': ['JEE', 'KEAM'],
            'top_colleges': ['IITs', 'NITs'],
            'career_path': 'Junior → Mid → Senior → IoT Architect',
            'day_to_day': ['Device programming', 'Sensor integration', 'Cloud connectivity', 'Testing'],
            'pros': ['Cutting-edge', 'Growing field', 'Diverse applications', 'Good salary'],
            'cons': ['Requires hardware knowledge', 'Complex debugging', 'Emerging field'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },

        # HEALTHCARE CAREERS (8)
        {
            'name': 'Doctor (MBBS)',
            'title': 'Doctor (MBBS)',
            'category': 'Healthcare',
            'subcategory': 'Medical',
            'description': 'Diagnose and treat patients, provide medical care',
            'detailed_description': 'Doctors diagnose illnesses, prescribe treatments, and care for patients. After MBBS, they can specialize in various fields like cardiology, neurology, pediatrics, etc.',
            'salary_range': '₹6-50 LPA',
            'min_salary': 600000,
            'max_salary': 5000000,
            'education': 'MBBS (5.5 years), MD/MS for specialization (3 years)',
            'skills': ['Medical knowledge', 'Diagnosis', 'Patient care', 'Communication', 'Decision-making', 'Empathy'],
            'required_skills': ['empathy', 'decision-making', 'attention-to-detail', 'communication', 'problem-solving'],
            'related_interests': ['helping-people', 'science', 'health', 'research', 'biology'],
            'related_subjects': ['Biology', 'Chemistry', 'Physics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Always in Demand',
            'work_environment': 'Hospitals/Clinics/Private Practice',
            'top_companies': ['Government hospitals', 'Private hospitals', 'Own practice'],
            'entrance_exams': ['NEET'],
            'top_colleges': ['AIIMS', 'CMC Vellore', 'Government Medical Colleges Kerala', 'Private Medical Colleges'],
            'career_path': 'Junior Doctor → Resident → Specialist → Senior Consultant → Hospital Director',
            'day_to_day': ['Patient consultations', 'Diagnosing illnesses', 'Prescribing treatments', 'Surgeries', 'Follow-ups'],
            'pros': ['Highly respected', 'Save lives', 'Job security', 'Good income', 'Social status'],
            'cons': ['Long education', 'Expensive education', 'Long working hours', 'High stress', 'Emotional toll'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Dentist (BDS)',
            'title': 'Dentist (BDS)',
            'category': 'Healthcare',
            'subcategory': 'Medical',
            'description': 'Specialize in oral health, treat dental problems',
            'detailed_description': 'Dentists focus on oral health, treating conditions of teeth, gums, and mouth. They can have their own clinics or work in hospitals.',
            'salary_range': '₹4-30 LPA',
            'min_salary': 400000,
            'max_salary': 3000000,
            'education': 'BDS (5 years), MDS for specialization (3 years)',
            'skills': ['Dental procedures', 'Manual dexterity', 'Patient care', 'Business management', 'Communication'],
            'required_skills': ['manual-dexterity', 'attention-to-detail', 'empathy', 'patience'],
            'related_interests': ['health', 'helping-people', 'science', 'medical'],
            'related_subjects': ['Biology', 'Chemistry', 'Physics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'High Demand',
            'work_environment': 'Dental clinics/Hospitals/Private practice',
            'top_companies': ['Own clinic', 'Hospital chains', 'Dental care centers'],
            'entrance_exams': ['NEET'],
            'top_colleges': ['Government Dental Colleges', 'Manipal', 'Private colleges'],
            'career_path': 'Junior Dentist → Senior Dentist → Specialist → Clinic Owner',
            'day_to_day': ['Patient consultations', 'Dental procedures', 'Cosmetic dentistry', 'Surgeries', 'Record keeping'],
            'pros': ['Own practice option', 'Good income', 'Respected profession', 'Work-life balance', 'Less emergency work'],
            'cons': ['Expensive equipment', 'Physically demanding', 'Initial investment high', 'Patient anxiety'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Nurse',
            'title': 'Nurse',
            'category': 'Healthcare',
            'subcategory': 'Nursing',
            'description': 'Provide direct patient care, assist doctors',
            'detailed_description': 'Nurses are essential healthcare workers who provide round-the-clock patient care. They work in hospitals, clinics, and can also work abroad.',
            'salary_range': '₹3-15 LPA',
            'min_salary': 300000,
            'max_salary': 1500000,
            'education': 'B.Sc Nursing (4 years), Diploma in Nursing (3 years)',
            'skills': ['Patient care', 'Medical procedures', 'Communication', 'Compassion', 'Quick thinking', 'Physical stamina'],
            'required_skills': ['empathy', 'communication', 'physical-stamina', 'quick-thinking', 'compassion'],
            'related_interests': ['helping-people', 'health', 'caregiving', 'medical'],
            'related_subjects': ['Biology', 'Chemistry'],
            'growth_potential': 'Good',
            'job_outlook': 'High Demand (esp. abroad)',
            'work_environment': 'Hospitals/Clinics/Home care',
            'top_companies': ['Hospitals', 'Nursing homes', 'International opportunities (US, UK, Middle East)'],
            'entrance_exams': ['Various state nursing exams'],
            'top_colleges': ['AIIMS', 'CMC', 'Government nursing colleges'],
            'career_path': 'Staff Nurse → Senior Nurse → Nursing Supervisor → Nursing Superintendent',
            'day_to_day': ['Patient care', 'Medication administration', 'Monitoring vitals', 'Assisting doctors', 'Documentation'],
            'pros': ['High demand globally', 'Job security', 'Helping people', 'Abroad opportunities', 'Respected'],
            'cons': ['Physically demanding', 'Long shifts', 'Emotional stress', 'Exposure to illness', 'Night shifts'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Pharmacist',
            'title': 'Pharmacist',
            'category': 'Healthcare',
            'subcategory': 'Pharmacy',
            'description': 'Dispense medications, advise on drug usage',
            'detailed_description': 'Pharmacists are medication experts who ensure safe and effective drug therapy. They can work in hospitals, retail pharmacies, or pharmaceutical companies.',
            'salary_range': '₹3-12 LPA',
            'min_salary': 300000,
            'max_salary': 1200000,
            'education': 'B.Pharm (4 years), M.Pharm (2 years), Pharm.D',
            'skills': ['Drug knowledge', 'Patient counseling', 'Attention to detail', 'Business management', 'Communication'],
            'required_skills': ['attention-to-detail', 'communication', 'knowledge-retention', 'empathy'],
            'related_interests': ['health', 'science', 'helping-people', 'chemistry'],
            'related_subjects': ['Chemistry', 'Biology'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Pharmacies/Hospitals/Pharmaceutical companies',
            'top_companies': ['Apollo Pharmacy', 'MedPlus', 'Hospitals', 'Own pharmacy'],
            'entrance_exams': ['State pharmacy exams', 'GPAT for M.Pharm'],
            'top_colleges': ['NIPs', 'JSS Mysore', 'Manipal', 'Government colleges'],
            'career_path': 'Junior Pharmacist → Senior Pharmacist → Chief Pharmacist → Pharmacy Owner',
            'day_to_day': ['Dispensing medications', 'Patient counseling', 'Inventory management', 'Prescriptions review', 'Drug information'],
            'pros': ['Own business option', 'Stable career', 'Healthcare sector', 'Good work-life balance'],
            'cons': ['Moderate salary', 'Standing for long hours', 'Dealing with regulations', 'Competitive'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Physiotherapist',
            'title': 'Physiotherapist',
            'category': 'Healthcare',
            'subcategory': 'Therapy',
            'description': 'Help patients recover from injuries through physical therapy',
            'detailed_description': 'Physiotherapists use physical methods like exercise, massage, and manual therapy to help patients recover from injuries and improve movement.',
            'salary_range': '₹3-15 LPA',
            'min_salary': 300000,
            'max_salary': 1500000,
            'education': 'BPT (Bachelor of Physiotherapy - 4.5 years), MPT',
            'skills': ['Anatomy knowledge', 'Manual therapy', 'Exercise prescription', 'Patient motivation', 'Assessment'],
            'required_skills': ['empathy', 'communication', 'physical-fitness', 'patience', 'motivation'],
            'related_interests': ['helping-people', 'health', 'sports', 'physical-fitness'],
            'related_subjects': ['Biology', 'Physical Education'],
            'growth_potential': 'Good',
            'job_outlook': 'Growing Demand',
            'work_environment': 'Hospitals/Clinics/Sports facilities/Home visits',
            'top_companies': ['Hospitals', 'Sports clubs', 'Own practice', 'Rehabilitation centers'],
            'entrance_exams': ['Various state/university exams'],
            'top_colleges': ['Manipal', 'CMC Vellore', 'Jamia Hamdard'],
            'career_path': 'Junior Physiotherapist → Senior → Consultant → Own Clinic',
            'day_to_day': ['Patient assessment', 'Treatment planning', 'Therapy sessions', 'Exercise guidance', 'Progress tracking'],
            'pros': ['Helping people recover', 'Good work-life balance', 'Own practice option', 'Sports opportunities'],
            'cons': ['Physically demanding', 'Patient compliance issues', 'Initial salary moderate'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Medical Lab Technician',
            'title': 'Medical Lab Technician',
            'category': 'Healthcare',
            'subcategory': 'Laboratory',
            'description': 'Perform laboratory tests and analysis',
            'detailed_description': 'Medical lab technicians perform diagnostic tests on blood, urine, and other body fluids to help doctors diagnose diseases.',
            'salary_range': '₹2-8 LPA',
            'min_salary': 200000,
            'max_salary': 800000,
            'education': 'B.Sc MLT (3 years), Diploma in MLT',
            'skills': ['Laboratory techniques', 'Equipment handling', 'Attention to detail', 'Analysis'],
            'required_skills': ['attention-to-detail', 'technical', 'analytical', 'precision'],
            'related_interests': ['science', 'health', 'laboratory', 'analysis'],
            'related_subjects': ['Biology', 'Chemistry'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Hospitals/Diagnostic labs',
            'top_companies': ['Hospitals', 'Diagnostic labs', 'Research institutions'],
            'entrance_exams': ['Various college entrances'],
            'top_colleges': ['Medical colleges', 'Paramedical institutes'],
            'career_path': 'Junior MLT → Senior MLT → Chief MLT → Lab Manager',
            'day_to_day': ['Sample collection', 'Running tests', 'Equipment maintenance', 'Report generation'],
            'pros': ['Stable career', 'Healthcare sector', 'Less patient interaction', 'Good work hours'],
            'cons': ['Moderate salary', 'Repetitive work', 'Exposure to samples'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Radiologist Technician',
            'title': 'Radiologist Technician',
            'category': 'Healthcare',
            'subcategory': 'Radiology',
            'description': 'Operate medical imaging equipment',
            'detailed_description': 'Radiologist technicians operate X-ray, CT, MRI machines to create images that help doctors diagnose medical conditions.',
            'salary_range': '₹3-10 LPA',
            'min_salary': 300000,
            'max_salary': 1000000,
            'education': 'B.Sc Radiology (3 years), Diploma in Radiology',
            'skills': ['Equipment operation', 'Patient positioning', 'Safety protocols', 'Image quality'],
            'required_skills': ['technical', 'attention-to-detail', 'communication', 'patient-care'],
            'related_interests': ['health', 'technology', 'imaging', 'medical'],
            'related_subjects': ['Physics', 'Biology'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Hospitals/Diagnostic centers',
            'top_companies': ['Hospitals', 'Diagnostic centers', 'Imaging clinics'],
            'entrance_exams': ['Various college entrances'],
            'top_colleges': ['Medical colleges', 'Paramedical institutes'],
            'career_path': 'Junior Tech → Senior Tech → Chief Tech → Department Head',
            'day_to_day': ['Patient positioning', 'Operating equipment', 'Image capture', 'Safety checks'],
            'pros': ['Good salary', 'Technology-based', 'Essential role', 'Less physical strain'],
            'cons': ['Radiation exposure', 'Shift work', 'Standing for long periods'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Veterinarian',
            'title': 'Veterinarian (Veterinary Doctor)',
            'category': 'Healthcare',
            'subcategory': 'Veterinary',
            'description': 'Treat and care for animals',
            'detailed_description': 'Veterinarians diagnose and treat illnesses in animals, perform surgeries, and provide preventive care for pets and livestock.',
            'salary_range': '₹3-15 LPA',
            'min_salary': 300000,
            'max_salary': 1500000,
            'education': 'BVSc & AH (5.5 years)',
            'skills': ['Animal care', 'Surgery', 'Diagnosis', 'Communication', 'Compassion'],
            'required_skills': ['empathy', 'patience', 'animal-handling', 'decision-making'],
            'related_interests': ['animals', 'health', 'helping', 'biology'],
            'related_subjects': ['Biology', 'Chemistry'],
            'growth_potential': 'Good',
            'job_outlook': 'Growing Demand',
            'work_environment': 'Veterinary clinics/Farms/Zoos',
            'top_companies': ['Own clinic', 'Pet hospitals', 'Government veterinary services'],
            'entrance_exams': ['NEET', 'State veterinary entrances'],
            'top_colleges': ['Veterinary colleges', 'Agricultural universities'],
            'career_path': 'Junior Vet → Senior Vet → Specialist → Clinic Owner',
            'day_to_day': ['Animal consultations', 'Surgeries', 'Vaccinations', 'Emergency care'],
            'pros': ['Love for animals', 'Own practice option', 'Rewarding work', 'Growing field'],
            'cons': ['Unpredictable hours', 'Emotional toll', 'Dealing with difficult cases'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },

        # ENGINEERING CAREERS (10)
        {
            'name': 'Mechanical Engineer',
            'title': 'Mechanical Engineer',
            'category': 'Engineering',
            'subcategory': 'Mechanical',
            'description': 'Design and develop mechanical devices and systems',
            'detailed_description': 'Mechanical engineers apply principles of mechanics, thermodynamics, and materials science to design and manufacture machines and systems.',
            'salary_range': '₹3-20 LPA',
            'min_salary': 300000,
            'max_salary': 2000000,
            'education': 'B.Tech/BE in Mechanical Engineering (4 years)',
            'skills': ['CAD/CAM', 'Thermodynamics', 'Manufacturing', 'Problem-solving', 'AutoCAD', 'SolidWorks'],
            'required_skills': ['technical', 'problem-solving', 'design', 'mathematics', 'creativity'],
            'related_interests': ['machines', 'building', 'design', 'physics', 'innovation'],
            'related_subjects': ['Physics', 'Mathematics', 'Chemistry'],
            'growth_potential': 'Good',
            'job_outlook': 'Moderate Demand',
            'work_environment': 'Factories/Design offices/Manufacturing plants',
            'top_companies': ['L&T', 'BHEL', 'Tata Motors', 'Mahindra', 'Automotive companies'],
            'entrance_exams': ['JEE Main', 'JEE Advanced', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Government Engineering Colleges'],
            'career_path': 'Junior Engineer → Design Engineer → Senior Engineer → Engineering Manager',
            'day_to_day': ['Design work', 'CAD modeling', 'Testing', 'Project coordination', 'Problem-solving'],
            'pros': ['Diverse industries', 'Hands-on work', 'Innovation', 'Foundation for many fields'],
            'cons': ['Competitive field', 'May require factory work', 'Slower salary growth than CS'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Civil Engineer',
            'title': 'Civil Engineer',
            'category': 'Engineering',
            'subcategory': 'Civil',
            'description': 'Design and oversee construction of buildings, roads, bridges',
            'detailed_description': 'Civil engineers plan, design, and supervise construction projects including infrastructure like roads, buildings, bridges, water supply systems.',
            'salary_range': '₹3-18 LPA',
            'min_salary': 300000,
            'max_salary': 1800000,
            'education': 'B.Tech/BE in Civil Engineering (4 years)',
            'skills': ['Structural analysis', 'AutoCAD', 'Project management', 'Site supervision', 'Building codes'],
            'required_skills': ['technical', 'problem-solving', 'project-management', 'supervision'],
            'related_interests': ['construction', 'building', 'infrastructure', 'design'],
            'related_subjects': ['Physics', 'Mathematics'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Construction sites/Offices',
            'top_companies': ['L&T', 'Tata Projects', 'NCC', 'Government PWD'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'CET Trivandrum', 'GEC Thrissur'],
            'career_path': 'Site Engineer → Project Engineer → Project Manager → Consultant',
            'day_to_day': ['Site visits', 'Design review', 'Project planning', 'Supervision', 'Quality control'],
            'pros': ['Infrastructure development', 'Visible results', 'Job security', 'Government opportunities'],
            'cons': ['Outdoor work', 'Travel required', 'Weather dependent', 'Moderate salary initially'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Electrical Engineer',
            'title': 'Electrical Engineer',
            'category': 'Engineering',
            'subcategory': 'Electrical',
            'description': 'Design and maintain electrical systems and power generation',
            'detailed_description': 'Electrical engineers work on power generation, transmission, distribution, and various electrical equipment and control systems.',
            'salary_range': '₹3-18 LPA',
            'min_salary': 300000,
            'max_salary': 1800000,
            'education': 'B.Tech/BE in Electrical Engineering (4 years)',
            'skills': ['Circuit design', 'Power systems', 'Control systems', 'MATLAB', 'AutoCAD'],
            'required_skills': ['technical', 'analytical', 'problem-solving', 'mathematics'],
            'related_interests': ['electricity', 'power', 'circuits', 'physics'],
            'related_subjects': ['Physics', 'Mathematics'],
            'growth_potential': 'Good',
            'job_outlook': 'Moderate Demand',
            'work_environment': 'Power plants/Factories/Offices',
            'top_companies': ['NTPC', 'Power Grid', 'BHEL', 'ABB', 'Siemens'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Government Engineering Colleges'],
            'career_path': 'Junior Engineer → Senior Engineer → Lead Engineer → Manager',
            'day_to_day': ['System design', 'Testing', 'Maintenance', 'Project work', 'Troubleshooting'],
            'pros': ['Essential field', 'Government jobs', 'Diverse applications', 'Job security'],
            'cons': ['May involve shift work', 'Dangerous if not careful', 'Competitive'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Electronics Engineer',
            'title': 'Electronics Engineer',
            'category': 'Engineering',
            'subcategory': 'Electronics',
            'description': 'Design and develop electronic equipment and systems',
            'detailed_description': 'Electronics engineers work on electronic systems from microchips to large communication systems, designing circuits and developing embedded systems.',
            'salary_range': '₹3-18 LPA',
            'min_salary': 300000,
            'max_salary': 1800000,
            'education': 'B.Tech/BE in Electronics & Communication (4 years)',
            'skills': ['Circuit design', 'Embedded systems', 'VLSI', 'Signal processing', 'PCB design'],
            'required_skills': ['technical', 'analytical', 'problem-solving', 'attention-to-detail'],
            'related_interests': ['electronics', 'circuits', 'technology', 'innovation'],
            'related_subjects': ['Physics', 'Mathematics'],
            'growth_potential': 'Good',
            'job_outlook': 'Moderate to High Demand',
            'work_environment': 'Offices/Labs/Manufacturing',
            'top_companies': ['Intel', 'Qualcomm', 'Samsung', 'Telecom companies'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'IIIT', 'Government colleges'],
            'career_path': 'Design Engineer → Senior Engineer → Lead → Manager',
            'day_to_day': ['Circuit design', 'Testing', 'Simulations', 'PCB layout', 'Documentation'],
            'pros': ['Technology field', 'Innovation', 'Good opportunities', 'Evolving field'],
            'cons': ['Competitive', 'Rapid technological changes', 'May need continuous learning'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Aerospace Engineer',
            'title': 'Aerospace Engineer',
            'category': 'Engineering',
            'subcategory': 'Aerospace',
            'description': 'Design and develop aircraft, spacecraft, satellites',
            'detailed_description': 'Aerospace engineers work on the design, development, and testing of aircraft and spacecraft. They can work with ISRO, DRDO, HAL, or private aerospace companies.',
            'salary_range': '₹4-25 LPA',
            'min_salary': 400000,
            'max_salary': 2500000,
            'education': 'B.Tech/BE in Aerospace Engineering (4 years)',
            'skills': ['Aerodynamics', 'Flight mechanics', 'Propulsion', 'CAD', 'Materials science'],
            'required_skills': ['technical', 'analytical', 'problem-solving', 'mathematics', 'innovation'],
            'related_interests': ['aviation', 'space', 'aircraft', 'science', 'physics'],
            'related_subjects': ['Physics', 'Mathematics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'Growing Demand',
            'work_environment': 'Research facilities/Manufacturing/Testing sites',
            'top_companies': ['ISRO', 'DRDO', 'HAL', 'Boeing', 'Airbus'],
            'entrance_exams': ['JEE Main', 'JEE Advanced', 'IIST entrance'],
            'top_colleges': ['IITs', 'IIST', 'IIT Bombay', 'IIT Madras'],
            'career_path': 'Junior Engineer → Design Engineer → Lead Engineer → Project Manager',
            'day_to_day': ['Design work', 'Simulations', 'Testing', 'Analysis', 'Project meetings'],
            'pros': ['Exciting field', 'Cutting-edge technology', 'ISRO opportunities', 'Prestigious'],
            'cons': ['Limited colleges', 'Competitive', 'Specialized field', 'May require relocation'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Chemical Engineer',
            'title': 'Chemical Engineer',
            'category': 'Engineering',
            'subcategory': 'Chemical',
            'description': 'Design and operate chemical manufacturing processes',
            'detailed_description': 'Chemical engineers work in industries producing chemicals, pharmaceuticals, food, and other products. They design processes and equipment.',
            'salary_range': '₹3-18 LPA',
            'min_salary': 300000,
            'max_salary': 1800000,
            'education': 'B.Tech/BE in Chemical Engineering (4 years)',
            'skills': ['Process design', 'Chemical reactions', 'Safety protocols', 'Equipment design'],
            'required_skills': ['technical', 'analytical', 'problem-solving', 'safety-conscious'],
            'related_interests': ['chemistry', 'processes', 'manufacturing', 'science'],
            'related_subjects': ['Chemistry', 'Physics', 'Mathematics'],
            'growth_potential': 'Good',
            'job_outlook': 'Moderate Demand',
            'work_environment': 'Chemical plants/Refineries/Labs',
            'top_companies': ['Reliance', 'ONGC', 'BPCL', 'Pharmaceutical companies'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'ICT Mumbai'],
            'career_path': 'Junior Engineer → Process Engineer → Senior → Manager',
            'day_to_day': ['Process monitoring', 'Quality control', 'Safety checks', 'Optimization'],
            'pros': ['Diverse industries', 'Good salary', 'Essential field'],
            'cons': ['Can be hazardous', 'Shift work', 'Factory environment'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Automobile Engineer',
            'title': 'Automobile Engineer',
            'category': 'Engineering',
            'subcategory': 'Automobile',
            'description': 'Design and develop vehicles and automotive systems',
            'detailed_description': 'Automobile engineers work on designing, developing, and manufacturing vehicles including cars, bikes, and commercial vehicles.',
            'salary_range': '₹3-18 LPA',
            'min_salary': 300000,
            'max_salary': 1800000,
            'education': 'B.Tech in Automobile/Mechanical Engineering',
            'skills': ['Vehicle design', 'CAD', 'Automotive systems', 'Testing'],
            'required_skills': ['technical', 'design', 'problem-solving', 'innovation'],
            'related_interests': ['vehicles', 'automobiles', 'design', 'engineering'],
            'related_subjects': ['Physics', 'Mathematics'],
            'growth_potential': 'Good',
            'job_outlook': 'Moderate Demand',
            'work_environment': 'Automotive companies/R&D centers',
            'top_companies': ['Tata Motors', 'Mahindra', 'Maruti Suzuki', 'Hyundai'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'VIT', 'SRM'],
            'career_path': 'Junior → Design Engineer → Senior → Manager',
            'day_to_day': ['Vehicle design', 'Testing', 'Quality control', 'R&D'],
            'pros': ['Exciting industry', 'Innovation', 'Good companies'],
            'cons': ['Competitive', 'Industry fluctuations', 'Demanding'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Biotechnology Engineer',
            'title': 'Biotechnology Engineer',
            'category': 'Engineering',
            'subcategory': 'Biotechnology',
            'description': 'Apply engineering principles to biological systems',
            'detailed_description': 'Biotechnology engineers work at the intersection of biology and engineering, developing medical devices, pharmaceuticals, and biotech products.',
            'salary_range': '₹3-15 LPA',
            'min_salary': 300000,
            'max_salary': 1500000,
            'education': 'B.Tech in Biotechnology (4 years)',
            'skills': ['Molecular biology', 'Bioprocess engineering', 'Lab techniques', 'Research'],
            'required_skills': ['analytical', 'research', 'technical', 'attention-to-detail'],
            'related_interests': ['biology', 'technology', 'research', 'medicine'],
            'related_subjects': ['Biology', 'Chemistry', 'Physics'],
            'growth_potential': 'Good',
            'job_outlook': 'Growing',
            'work_environment': 'Labs/Research centers/Pharmaceutical companies',
            'top_companies': ['Biocon', 'Pharmaceutical companies', 'Research institutions'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'VIT'],
            'career_path': 'Research Assistant → Scientist → Senior Scientist',
            'day_to_day': ['Research', 'Experiments', 'Data analysis', 'Documentation'],
            'pros': ['Cutting-edge field', 'Research opportunities', 'Impactful work'],
            'cons': ['Slower career growth', 'Requires higher education', 'Competitive'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Environmental Engineer',
            'title': 'Environmental Engineer',
            'category': 'Engineering',
            'subcategory': 'Environmental',
            'description': 'Develop solutions to environmental problems',
            'detailed_description': 'Environmental engineers work on waste management, pollution control, water treatment, and sustainable development.',
            'salary_range': '₹3-15 LPA',
            'min_salary': 300000,
            'max_salary': 1500000,
            'education': 'B.Tech in Environmental Engineering',
            'skills': ['Waste management', 'Water treatment', 'Environmental assessment', 'Sustainability'],
            'required_skills': ['analytical', 'problem-solving', 'environmental-awareness', 'technical'],
            'related_interests': ['environment', 'sustainability', 'conservation', 'ecology'],
            'related_subjects': ['Biology', 'Chemistry', 'Physics'],
            'growth_potential': 'Good',
            'job_outlook': 'Growing',
            'work_environment': 'Field/Offices/Government agencies',
            'top_companies': ['Government', 'Consulting firms', 'Environmental agencies'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs', 'Anna University'],
            'career_path': 'Junior Engineer → Project Engineer → Senior → Manager',
            'day_to_day': ['Site assessments', 'Project planning', 'Monitoring', 'Reporting'],
            'pros': ['Meaningful work', 'Growing field', 'Environmental impact'],
            'cons': ['Moderate salary', 'Field work', 'Less glamorous'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        {
            'name': 'Industrial Engineer',
            'title': 'Industrial Engineer',
            'category': 'Engineering',
            'subcategory': 'Industrial',
            'description': 'Optimize complex processes and systems',
            'detailed_description': 'Industrial engineers improve efficiency in manufacturing, logistics, and business operations by optimizing processes and reducing waste.',
            'salary_range': '₹3-16 LPA',
            'min_salary': 300000,
            'max_salary': 1600000,
            'education': 'B.Tech in Industrial Engineering',
            'skills': ['Process optimization', 'Six Sigma', 'Supply chain', 'Quality control'],
            'required_skills': ['analytical', 'problem-solving', 'optimization', 'systems-thinking'],
            'related_interests': ['efficiency', 'optimization', 'systems', 'management'],
            'related_subjects': ['Mathematics', 'Physics'],
            'growth_potential': 'Good',
            'job_outlook': 'Steady Demand',
            'work_environment': 'Manufacturing/Offices',
            'top_companies': ['All manufacturing companies', 'Consulting firms'],
            'entrance_exams': ['JEE Main', 'KEAM'],
            'top_colleges': ['IITs', 'NITs'],
            'career_path': 'Junior Engineer → Process Engineer → Senior → Manager',
            'day_to_day': ['Process analysis', 'Optimization', 'Project management', 'Quality improvement'],
            'pros': ['Versatile', 'Multiple industries', 'Management opportunities'],
            'cons': ['Less technical', 'Moderate salary', 'Factory environment'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },

        # Add more careers... (Business, Creative, Law, etc.)
        # Due to character limits, I'll continue with key careers from other categories

        # BUSINESS CAREERS (Sample)
        {
            'name': 'Chartered Accountant (CA)',
            'title': 'Chartered Accountant (CA)',
            'category': 'Business',
            'subcategory': 'Finance & Accounting',
            'description': 'Manage finances, auditing, taxation, and financial advisory',
            'detailed_description': 'CAs are highly qualified finance professionals who handle accounting, auditing, taxation, and financial consulting.',
            'salary_range': '₹6-80 LPA',
            'min_salary': 600000,
            'max_salary': 8000000,
            'education': 'CA (3-5 years after 12th)',
            'skills': ['Accounting', 'Taxation', 'Auditing', 'Financial analysis', 'Business advisory'],
            'required_skills': ['analytical', 'attention-to-detail', 'problem-solving', 'communication'],
            'related_interests': ['finance', 'accounting', 'numbers', 'business', 'analysis'],
            'related_subjects': ['Accountancy', 'Mathematics', 'Economics'],
            'growth_potential': 'Excellent',
            'job_outlook': 'High Demand',
            'work_environment': 'Offices/Client sites/Own practice',
            'top_companies': ['Big 4 (Deloitte, EY, KPMG, PwC)', 'Corporate companies', 'Own practice'],
            'entrance_exams': ['CA Foundation', 'CA Intermediate', 'CA Final'],
            'top_colleges': ['ICAI (Institute of Chartered Accountants of India)'],
            'career_path': 'Article Assistant → CA → Senior CA → Partner → Own Firm',
            'day_to_day': ['Auditing', 'Tax planning', 'Financial reporting', 'Client meetings', 'Advisory services'],
            'pros': ['High prestige', 'Excellent salary', 'Own practice option', 'Respected profession', 'Job security'],
            'cons': ['Very tough exams', 'Long study period', 'High pressure', 'Demanding during tax season'],
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow()
        },
        # Add remaining 20+ careers here...
        # (MBA Graduate, Investment Banker, Digital Marketing Manager, etc.)
        # (Creative: Graphic Designer, Architect, Fashion Designer, UI/UX)
        # (Law: Lawyer, Corporate Lawyer)
        # (Education: Professor/Teacher)
        # (Science: Research Scientist)
        # (Government: IAS/IPS Officer)
    ]
    
    print(f"📝 Inserting {len(all_careers)} careers...")
    result = db.careers.insert_many(all_careers)
    print(f"✅ Successfully inserted {len(result.inserted_ids)} careers!")
    
    # Verify
    total = db.careers.count_documents({})
    print(f"\n📊 Total careers in database: {total}")
    
    # Show by category
    pipeline = [
        {"$group": {"_id": "$category", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}}
    ]
    categories = list(db.careers.aggregate(pipeline))
    
    print("\n📊 Careers by Category:")
    for cat in categories:
        print(f"   {cat['_id']}: {cat['count']} careers")
    
    print("\n" + "=" * 60)
    print("✨ SUCCESS!")
    print("=" * 60)
    print(f"\n🌐 Visit: http://localhost:3000/careers")
    print("🔄 Press Ctrl+Shift+R in browser to refresh")
    
except Exception as e:
    print(f"\n❌ ERROR:")
    print(f"Error: {str(e)}")
    import traceback
    traceback.print_exc()